version: '3.8'

services:
  timecapsule-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - timecapsule-network

  # Optional: If you want to add a backend service later
  # timecapsule-backend:
  #   image: your-backend-image
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - DATABASE_URL=your-database-url
  #   networks:
  #     - timecapsule-network

networks:
  timecapsule-network:
    driver: bridge

volumes:
  timecapsule-data:
